core/templatetags/urls.py
from typing import Optional, Any, Dict
from django import urls, template
register = template.Library()


@register.simple_tag(takes_context=True)
def translate_url(context: Dict[str, Any], language: Optional[str]) -> str:
    """Get the absolute URL of the current page for the specified language.

    Usage:
        {% translate_url 'en' %}
    """
    url = context['request'].build_absolute_uri()
    return urls.translate_url(url, language)

core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from core.views import *
from core.controllers import *
from core.order_api import *
from core.pay import * 
from django.contrib import admin
from core.admin import (
  manager_admin_site,
)
from filebrowser.sites import site
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
  path('rosetta/',           include('rosetta.urls')),
  path('tinymce/',           include('tinymce.urls')),
  path('i18n/',              include('django.conf.urls.i18n')),
  path('jsi18n/',            JavaScriptCatalog.as_view(), name='javascript-catalog'),
  path('admin/filebrowser/', site.urls),
  path('set_lang/<lang>/',   set_lang,       name="set_lang"),
  path('test_mail/',         test_mail,      name='test_mail'),
  path('test/',              test,           name='test'),
  path('set_params/',        set_params,     name='set_params'),
  path('get_seats/',         get_seats,      name="get_seats"),
  path('create_order/',      create_order,   name='create_order'),
  path('create_bus_comment/<bus_pk>/', create_bus_comment, name='create_bus_comment'),
  path('create_question/',    create_question,name='create_question'),
  path('pay/',               pay,            name='pay'),
  path('pay_callback/',      pay_callback,   name='pay_callback'),
  path('create_multiple_races/', create_multiple_races, name='create_multiple_races'),
]
urlpatterns += i18n_patterns(
  path('admin+/',       admin.site.urls),
  path('admin/',        manager_admin_site.urls),
  path('',              index,        name='index'),
  path('blog/',         blog,         name='blog'),
  path('post/<pk>',     post_detail,  name='post_detail'),
  path('contact_us/',   contact_us,   name='contact_us'),
  path('park/',         park,         name='park'),
  path('order/',        order,        name='order'),
  path('about_us/',     about_us,     name='about_us'),
  path('thank_you/',    thank_you,    name='thank_you'),
  prefix_default_language=True,
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from django.db import models
from datetime import datetime, timedelta
from django.db import models
from django.conf import settings 
from django.utils.translation import ugettext as _


# %Y-%m-%d 2006-10-25
# %m/%d/%Y 10/25/2006
# %m/%d/%y 10/25/06
# %H:%M:%S 14:30:59
# %H:%M    14:30


class Time(models.Model):
  time = models.TimeField("Время рейса", blank=True, null=True)
  def __str__(self): return f'{self.time}'
  class Meta: verbose_name = 'Время остановок'; verbose_name_plural = 'Времена остановок'; 


class Direction(models.Model):
  code  = models.CharField(max_length=20, blank=True, null=True, unique=True)
  name  = models.CharField("Направление",max_length=120, blank=True, null=True)
  times = models.ManyToManyField('core.Time', blank=True, null=True)
  stops = models.ManyToManyField('core.Stop', blank=True, null=True)
  # cities_front
  # cities_backward - на случай если маршруты туда-обратно отличаются
  def __str__(self):return f'{self.name}'  
  class Meta: verbose_name = 'Направление'; verbose_name_plural = 'Направления'; 


class Stop(models.Model):
  name = models.CharField("Остановка",max_length=120, blank=True, null=True)
  def __str__(self): return f'{self.name}'
  class Meta: verbose_name = 'Остановка'; verbose_name_plural = 'Остановки'


class Seat(models.Model):
  number = models.CharField("Номер места",max_length=120, blank=True, null=True)
  def __str__(self): return f'{self.number}'
  class Meta: verbose_name = 'Место'; verbose_name_plural = 'Места'; 


class Race(models.Model):
  direction = models.ForeignKey('core.Direction', verbose_name="Направление",on_delete=models.CASCADE, blank=True, null=True)
  time      = models.ForeignKey('core.Time', on_delete=models.CASCADE, verbose_name='Время отправки',blank=True, null=True)
  date      = models.DateField('Дата отправки',blank=True, null=True)
  price     = models.DecimalField('Стоимость',max_digits=10, decimal_places=2, blank=True, null=True, default=10)
  is_full   = models.BooleanField('Полностью заполнен',default=False, blank=True, null=True)
  def __str__(self): return f'{self.direction}, {self.time}, {self.date}, {self.price} UAH'# ,{self.ordered_seats.all()}' 
  class Meta: verbose_name = 'Рейс'; verbose_name_plural = 'Рейсы'


class SeatInOrder(models.Model):
  seat  = models.ForeignKey('core.Seat', verbose_name="Место" ,blank=True, null=True, on_delete=models.CASCADE)
  order = models.ForeignKey('core.Order',verbose_name="Заказ" ,related_name='seats', blank=True, null=True, on_delete=models.CASCADE)
  race  = models.ForeignKey('core.Race', verbose_name="Рейс" ,related_name='seats', blank=True, null=True, on_delete=models.CASCADE)
  def __str__(self): return f'{self.seat}|{self.order.sk}|{self.race}'
  class Meta: verbose_name = 'Место в заказе'; verbose_name_plural = 'Места в заказе'; 


class StopInRace(models.Model):
  stop = models.ForeignKey('core.Stop', verbose_name='Остановка',      on_delete=models.CASCADE, blank=True, null=True)
  time = models.ForeignKey('core.Time', verbose_name='Время остановки',on_delete=models.CASCADE, blank=True, null=True)
  race = models.ForeignKey('core.Race', verbose_name='Рейс',           on_delete=models.CASCADE, blank=True, null=True, related_name='stops', )
  def __str__(self): return f'{self.time.time}|{self.stop.name}'
  class Meta: verbose_name = 'Остановка в рейсе'; verbose_name_plural = 'Остановки в рейсе'


class Order(models.Model):
  full_name = models.CharField(_("Полное имя"),max_length=120, blank=True, null=True)
  phone     = models.CharField("Номер телефона",max_length=120, blank=True, null=True)
  email     = models.EmailField("Емайл",blank=True, null=True)
  departion = models.CharField("Город отправления",max_length=120,blank=True, null=True)
  arrival   = models.CharField("Город прибытия",max_length=120,blank=True, null=True)

  sk        = models.CharField(max_length=120, blank=True, null=True, unique=True)
  race      = models.ForeignKey('core.Race', related_name='orders',verbose_name="Рейс",on_delete=models.CASCADE, blank=True, null=True)

  ordered   = models.BooleanField('завершен', default=False)
  pdf       = models.FileField("Билет",upload_to='pdfs/', null=True, blank=True)
  created   = models.DateTimeField("Создан",auto_now_add=True, auto_now=False, blank=True, null=True)
  updated   = models.DateTimeField("Обновлен",auto_now_add=False, auto_now=True, blank=True, null=True)

  @property
  def price(self):
    price = 0
    for seat in self.seats.all():
      price += seat.race.price
    return price
    # return self.race.price
  def __str__(self): return f'{self.sk}|{self.full_name}|{self.race}'
  class Meta: verbose_name = 'Заказ'; verbose_name_plural = 'Заказы'


class Payment(models.Model):
  status              = models.CharField(max_length=120, blank=True, null=True)
  ip                  = models.CharField(max_length=120, blank=True, null=True)
  amount              = models.CharField(max_length=120, blank=True, null=True)
  currency            = models.CharField(max_length=120, blank=True, null=True)
  order               = models.OneToOneField(Order, verbose_name='Заказ',on_delete=models.CASCADE, blank=True, null=True)
  sender_phone        = models.CharField(max_length=120, blank=True, null=True)
  sender_first_name   = models.CharField(max_length=120, blank=True, null=True)
  sender_last_name    = models.CharField(max_length=120, blank=True, null=True)
  sender_card_mask2   = models.CharField(max_length=120, blank=True, null=True)
  sender_card_bank    = models.CharField(max_length=120, blank=True, null=True)
  sender_card_type    = models.CharField(max_length=120, blank=True, null=True)
  sender_card_country = models.CharField(max_length=120, blank=True, null=True)
  timestamp           = models.DateTimeField(verbose_name='Время',auto_now_add=True, blank=True, null=True)
  def __str__(self):
    return f'{self.order}|{self.amount}|{self.currency}'
  class Meta: verbose_name = 'Оплата'; verbose_name_plural = 'Оплата'; 


class Question(models.Model):
  name     = models.CharField("Имя",max_length=120)
  email    = models.EmailField("Емайл")
  phone    = models.CharField("Телефон",max_length=120)
  question = models.CharField("Тип вопроса",max_length=120)
  message  = models.TextField("Вопрос")
  created  = models.DateTimeField("Создан",auto_now_add=True, auto_now=False, blank=True, null=True)
  updated  = models.DateTimeField("Обновлен",auto_now_add=False, auto_now=True, blank=True, null=True)
  def __str__(self):
    return f'{self.name}|{self.email}|{self.phone}|{self.question}|{self.message}'
  class Meta:
    verbose_name = _("Вопрос")
    verbose_name_plural = _("Вопросы")


class Page(models.Model):
  name  = models.CharField(max_length=120, blank=True, null=True)
  title = models.CharField(max_length=120, blank=True, null=True)
  desc  = models.CharField(max_length=120, blank=True, null=True)
  url   = models.CharField(max_length=120, blank=True, null=True)
  def __str__(self):
    return f'{self.name}|{self.url}|{self.title}'


class Post(models.Model):
  title   = models.CharField(verbose_name=_("Заголовок"),max_length=120, blank=True, null=True)
  content = HTMLField(verbose_name=_("Контент"), blank=True, null=True)  
  slug    = models.SlugField(verbose_name=_("Ссылка"), blank=True, null=True, max_length=255)
  image   = models.ImageField(verbose_name=_("Картинка"), blank=True, null=True)
  created = models.DateTimeField(verbose_name=_("Создан"), auto_now_add=True, auto_now=False)
  updated = models.DateTimeField(verbose_name=_("Обновлен"), auto_now_add=False, auto_now=True)
  def __str__(self):
    return f'{self.title}'
  class Meta:
    verbose_name = _('Пост')
    verbose_name_plural = _('Посты')





class BusGood(models.Model):
  text = models.TextField()
  bus  = models.ForeignKey(to="core.Bus", on_delete=models.CASCADE, related_name="goods", blank=True, null=True)


class BusComment(models.Model):
  text = models.TextField()
  bus  = models.ForeignKey(to='core.Bus', on_delete=models.CASCADE, related_name='comments', blank=True, null=True)


class Bus(models.Model):
  name  = models.CharField(max_length=120)
  photo = models.ImageField()
  def __str__(self):
    return self.name

core/forms.py
from django import forms
from core.models import *
from django.contrib.admin.widgets import AdminDateWidget


CHOICES = (
  ("Основные вопросы","Основные вопросы"),
  ("...","..."),
  ("...","..."),
  ("...","..."),
)



class RaceForm(forms.ModelForm):
  date_from = forms.DateField(required=True, label='Диапазон от', help_text="Вводить дату в формате год-месяц-день(2019-06-23)")#, widget=forms.SelectDateWidget())
  date_to = forms.DateField(required=True, label='Диапазон до', help_text="Вводить дату в формате год-месяц-день(2019-07-15)")#, widget=forms.SelectDateWidget())
  class Meta:
    model = Race
    exclude = ['date', 'is_full']




SEAT_CHOICES = (
  ('1','1'),   ('2','2'),   ('3','3'),
  ('4','4'),   ('5','5'),   ('6','6'),
  ('7','7'),   ('8','8'),   ('9','9'),
  ('10','10'), ('11','11'), ('12','12'), ('13','13'),
  ('14','14'), ('15','15'), ('16','16'), ('17','17'),
  ('18','18'), ('19','19'), ('20','21'), ('21','21'),
)
PAYMENT_CHOICES = (
  ('manager', 'Заказ у менеджера'),
  ('privat24', 'Предоплата на карту Приват24'),
)

core/controllers.py
from django.shortcuts import (render, get_object_or_404, reverse, redirect)
from core.utils import get_sk
from django.utils import timezone 
from django.views.decorators.csrf import csrf_exempt
from django.utils import translation
from django.utils.translation import ugettext as _
from core.forms import *
from core.models import *
from core.utils import *
from django.contrib import messages
from datetime import datetime, date, time, timedelta
from django.utils.translation import ugettext as _




def create_multiple_races(request):
  form = RaceForm(request.POST or None)
  if request.method == 'POST':
    date_from = request.POST.get('date_from', '')
    date_to   = request.POST.get('date_to', '')
    start     = datetime.strptime(date_from, '%Y-%m-%d')
    end       = datetime.strptime(date_to, '%Y-%m-%d')
    direction = Direction.objects.get(id=request.POST.get('direction', ''))
    time      = Time.objects.get(id=request.POST.get('time', ''))
    dates     = []
    while start <= end:
      dates.append(start.date())
      start += timedelta(days=1)
    for date in dates:
      print(date)
      race, created = Race.objects.get_or_create(
        direction=direction,
        date=date,
        time=time,
      )
      if created:
        race.price=request.POST.get('price','')
        race.save()
  print(request.POST)
  return render(request, 'create_multiple_races.html', locals())


def set_lang(request, lang=None):
    translation.activate(lang)
    request.session[translation.LANGUAGE_SESSION_KEY] = lang
    # lang = request.POST['language']
    url = request.META['HTTP_REFERER'].split('/')
    url[3] = lang
    url = '/'.join(url)
    return redirect(url)



def test_mail(request):
  # http://localhost:8000/en/admin/order/order/337/change/
  order = Order.objects.get(sk='vbekd254fi79e4c87ofb5gifg8xiw8qy')
  # save_user_order(order)
  # return redirect('index')
  save_user_order(order)
  send_user_mail(order)
  return redirect('test_mail')


def create_bus_comment(request, bus_pk):
  print(request.POST)
  BusComment.objects.create(
    text = request.POST.get('text'),
    bus  = Bus.objects.get(pk=bus_pk),
  )
  send_comment_mail()
  try: return redirect(request.META.get('HTTP_REFERER'))
  except: return redirect('/')


def create_question(request):
  Contact.objects.create(
    name     = request.POST.get('name', ''),
    email    = request.POST.get('email', ''),
    message  = request.POST.get('comment', ''),
    question = request.POST.get('question', ''),
    phone    = request.POST.get('phone', ''),
  )
  send_contact_mail()
  messages.success(request, _('Запитання було добавлений у адмінку'))
  try: return redirect(request.META.get('HTTP_REFERER'))
  except: return redirect('contact_us')

core/views.py
from django.shortcuts import (render, get_object_or_404)
from core.utils import (get_sk)
from core.models import (
  Order, Post, Bus, BusComment
)
from django.utils import timezone


def test(request):
  request.session.cycle_key()
  Order.objects.get_or_create(sk=get_sk(request))
  created_time = timezone.now()-timezone.timedelta(minutes=20)
  orders = Order.objects.filter(
    created__lte=created_time,
    ordered=False
  ).delete()
  return render(request, 'test.html', locals())


def order(request):
  request.session.cycle_key()
  created_time = timezone.now()-timezone.timedelta(minutes=20)
  orders = Order.objects.filter(
    created__lte=created_time,
    ordered=False
  ).delete()
  return render(request, 'order.html', locals())


def index(request):
  print(get_sk(request))
  bus_comments = BusComment.objects.all()
  print(bus_comments)
  return render(request, 'index.html', locals())


def park(request):
  buses = Bus.objects.all()
  print(get_sk(request))
  return render(request, 'park.html', locals())


def about_us(request):
  print(get_sk(request))
  return render(request, 'about_us.html', locals())


def contact_us(request):
  return render(request, 'contact_us.html', locals())


def blog(request):
  posts = Post.objects.all()
  return render(request, 'blog.html', locals())


def post_detail(request, pk):
  post = get_object_or_404(Post, pk=pk)
  comments = post.comments.filter(moderated=True)
  return render(request, 'post_detail.html', locals())


def thank_you(request):
  return render(request, 'thank_you.html', locals())

core/templates/create_multiple_races.html
{% extends 'admin/base_site.html' %}
{% load i18n %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo;
        <a href="/admin/core">Core</a>
        &rsaquo;
        <a href="/admin/core/race">Рейсы</a>
        &rsaquo; Добавить несколько рейсов
    </div>
{% endblock %}
{% block content%}
<form action="{% url 'create_multiple_races' %}" method="POST">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Создать"/>
</form>
{% endblock content%}

core/templates/races_change_list.html
{% extends 'admin/change_list.html' %}
{% block object-tools %}

    {{block.super}}

{% endblock object-tools %}
{% block object-tools-items %}
    <a class="addlink" href="{% url 'create_multiple_races' %}">Добавить несколько рейсов</a>
    {{block.super}}

{% endblock object-tools-items %}

core/templates/test.html
<div class="order_info"></div>

<form method='POST' action="{% url 'personal' %} " id="form"> {% csrf_token %}
  <br/>
  <label for="id_direction">Направление:</label>
  <select name="direction" required="" id="id_direction">
  </select>
  <br/>
  <label for="id_date">Дата поездки:</label>
  <input type="text" name="date" class="datepicker-here form__element_calendar" required="" id="id_date">
  <br/>
  <label for="id_time">Рейс:</label>
  <select name="time" required="" id="id_time">
  </select>
  <br/>
  <label>Свободные места:</label>
  <ul id="id_seats">
  </ul>
  <br/>
  <label for="id_full_name">Имя и фамилия:</label>
  <input type="text" name="full_name" maxlength="100" required="" id="id_full_name">
  <br/>
  <label for="id_phone">Телефон:</label>
  <input type="text" name="phone" placeholder="Телефон" required="" id="id_phone">
  <br/>
  <label for="id_email">Email:</label>
  <input type="email" name="email" maxlength="100" required="" id="id_email">
  <br/>
  <label for="id_payment">Оплата:</label>
  <select name="payment" id="id_payment">
    <option value="manager">Заказ у менеджера</option>
    <option value="privat24">Предоплата на карту Приват24</option>
  </select>
  <br/>
  <label for="id_departion">Город отправления:</label>
  <select name="departion" required="" id="id_departion">
  </select>
  <br/>
  <label for="id_arrival">Город прибытия:</label>
  <select name="arrival" required="" id="id_arrival">
  </select>
  <br/>
  <button class="btn btn-primary" type="submit">Замовити</button>
</form>


<style>
  input[type='checkbox']{display:none; }
  .ordered              {color:white; background:darkgoldenrod; border:1px solid darkgoldenrod}
  input:checked ~ label {color:white; background:green;         border:1px solid green }
  .unordered            {color:black; background:white;         border:1px solid black}
</style>

<script src="/static/js/jquery-3.4.1.min.js" type="text/javascript"></script>
<script>

var id_full_name = document.querySelector('#id_full_name');
var id_phone     = document.querySelector('#id_phone');
var id_email     = document.querySelector('#id_email');
var id_payment   = document.querySelector('#id_payment');
var id_departion = document.querySelector('#id_departion');
var id_arrival   = document.querySelector('#id_arrival');
var form         = document.querySelector('#form');
var SITE_NAME         = window.location.origin
var order_info_url    = SITE_NAME+'/get_order_info/'
var set_params_url    = SITE_NAME+'/set_params/'
var skj;


function get_order_info(){
$.ajax({ url:order_info_url, type:'GET', async:true,success: function(response){
  // console.log('get_order_info:', response)
  var sk;
  var dir;
  var date;
  var time;
  var seats = [];
  try{sk   = response.order_sk}catch{}
  try{dir  = response.direction}catch{}
  try{date = response.date}catch{}
  try{time = response.order_time}catch{}
  response.order_seats.forEach(function(seat){
    //seats.push(seat.seat)
    seats.push(seat)
  })
  var result = `
  <ul>
    <li>${sk}</li>
    <li>${dir}</li>
    <li>${date}</li>
    <li>${time}</li>
    <li>${seats}</li>
  </ul>
  `;
  // console.log(result)
  document.querySelector('.order_info').innerHTML = result
  skj = response.order_sk
  // document.querySelector('.order_info').innerHTML = 123
  // skj = 123
}})}








function set_params(e){
var data = {}
try{
  // data.direction = id_direction.options[id_direction.selectedIndex].text
  // id_direction.options[id_direction.options.selectedIndex].selected = true;

  data.direction = id_direction.value
}catch(error){
//  console.log('direction error',error)
}
try{
  data.date = id_date.value
}catch(error){
//  console.log('date error',error)
}
try{
  data.time = id_time.value
}catch(error){
//  console.log('time error',error)
}
try{
  var array = []
  var checkboxes = document.querySelectorAll('input[type=checkbox]:checked');
  console.log( checkboxes.length);
  console.log( checkboxes);
  for (var i = 0; i < checkboxes.length; i++) {
    array.push(checkboxes[i].value)
  }
  console.log(array);
  data.seats = array
  console.log(data.seats);
  console.log(data);
}catch(error){
//  console.log('seats error',error)
}
$.ajax({url:set_params_url, data:data, type:'POST', async:true, success:function(data){
  get_order_info();
  console.log(data)
  var direction_result = '';
  var city_result = '';
  var time_result = '';
  // var date_result = '';
  var seats_result = '';
  var i = 0;



  try{
  order_direction = data.order_direction
  }catch{
  order_direction = ''
  }
  try{
  data.directions.forEach(direction => {
    if(direction.name == order_direction){
      direction_result += `<option value="${direction.code}" selected>${direction.name}</option>`;
    }else{
      direction_result += `<option value="${direction.code}">${direction.name}</option>`;
    }
  });
  id_direction.innerHTML = direction_result;
  }catch(error){
  //  console.log('direction error',error)
  }


  // try{
  // date_name = data.order_date
  // }catch{
  // date_name = ''
  // }

  // try{
  //   data.dates.forEach(date => {
  //     date_result += `<br>${date}`
  //   })
  //   id_date_result = date_result;
  // }catch(error){
  //  //  console.log('date error',error)
  // }


  try{
  order_time = data.order_time
  }catch{
  order_time = ''
  }
  try{
  data.times.forEach(time => {
    if(time == order_time){
    time_result += `<option value="${time}" selected>${time}</option>`;
    }else{
    time_result += `<option value="${time}">${time}</option>`;
    }
  });
  id_time.innerHTML = time_result;
  }catch(error){
  //  console.log('times error',error)
  }


  function get_seat(x){
    return data.seats_in_order.find( (seat_in_order) => seat_in_order.number === x.toString())
  }
  try{
  data.seats_numbers.forEach((seat)=>{
    try{
      var skd = get_seat(seat).order_sk
      // var skd = data.seats_in_order.find( (seat_in_order) => seat_in_order.number.toString() === seat.toString())
      // новое
      var skj = data.order_sk
      if(skd == skj){
        seats_result += `<span class="unordered"><input checked="" type="checkbox" name="seats" value="${seat}" id="id_seats_${i}"><label for="id_seats_${i}">${seat}</label></span>`;
        i+=1;
      }
      if (skd != undefined && skd != skj){
        seats_result += `<span class="ordered"> ${seat} </span>`;
        i+=1;
      }
    }catch(error){
    //  console.log('1', error)
      seats_result += `<span class="unordered"><input type="checkbox" name="seats" value="${seat}" id="id_seats_${i}"><label for="id_seats_${i}">${seat}</label></span>`;
      i+=1;
    }
  })
  id_seats.innerHTML = seats_result;
  }catch(error){
  //  console.log('2', error)

  }


  try{
    departion_city = data.order.departion
    arrival_city = data.order.arrival
  }catch{
    departion_city = "";
    arrival_city = "";
  }
  try{
  data.cities.forEach(city => {
    // console.log(city)
    city_result += `<option value="${city}">${city}</option>`;
  });
  id_departion.innerHTML = city_result
  id_arrival.innerHTML = city_result
  }catch(error){
  //  console.log('cities error',error)
  }

  try{
  }catch(error){
  //  console.log('... error',error)
  }
}})}



document.addEventListener('DOMContentLoaded', function(){
  set_params();
  get_order_info();
  $('#id_direction').on('change', set_params)
  $('#id_date').on('change', set_params)
  $('#id_time').on('change', set_params)
  $('#id_seats').on('change', set_params)
})
</script>